### ISSUE TITLE
Задача "Да-нетки"

### ISSUE THREAD

**Issue by vovs03** [Sergei089/python_ex#21]
# Задача "Да-нетки"
Написать программу которая случайным образом возвращает один из вариантов ответа: `"Да"` или `"Нет"`.

-  [x] Использовать библиотеку `import random`(для масштабирования(расширения) количества вариантов перебора).
- [x] список `vars = ("Да" ,"Нет")`
- [x] функция `get_random_vars()`

---

> 2022-12-12 11.00 - 12.00 `16 занятие`

**Comment by Sergei089** [comment]
import random as r

vars = ("Да", "Нет")

def get_random_vars(vars):
	# генератор 0,1 `g <- generator`
	g = (r.randint(range(0,1)))

	# функция должна рандомно выбирать да или нет!
	# random_index = random.randint(0,len(vars) -1)
	print(vars[g])
get_random_vars(vars)
