### ISSUE TITLE
Задача d17_demo1 Return Negative

### ISSUE THREAD

**Issue by vovs03** [Sergei089/python_ex#24]
# Return Negative

- [x] https://www.codewars.com/kata/55685cd7ad70877c23000102/train/python

**Comment by vovs03** [comment]
```python    
if number <= 0:
        return number
#     elif number == 0:
#         return 0
    else: # делание чисел реально отрицательными
        return -abs( number )
```

**Comment by Sergei089** [comment]
![Screenshot from 2022-12-20 11-10-15](https://user-images.githubusercontent.com/116675434/208616336-9d577370-e761-4ae2-9a1f-9799bcff6c56.png)

**Comment by Sergei089** [comment]
https://www.codewars.com/users/Sergei089

**Comment by vovs03** [comment]
# Твой прогресс

>  Твой **Профиль** `Sergei089` на кодварс: https://www.codewars.com/users/Sergei089

![208616336-9d577370-e761-4ae2-9a1f-9799bcff6c56](https://user-images.githubusercontent.com/21124057/208616941-c322f879-4f27-4286-9e35-55f0bacd25cd.png)
