### ISSUE TITLE
codewars.8kyu/Beginner - Reduce but Grow

### ISSUE THREAD

**Issue by Sergei089** [Sergei089/python_ex#27]
https://www.codewars.com/kata/57f780909f7e8e3183000078/train/python
```python
def grow(arr):
    for i in arr:
         a = i * i
    return a
```

**Comment by vovs03** [comment]
# Моё решение

> Запрос: `python 3 перемножить все элементы массива`

>  🍏 `Ответ` : https://ru.stackoverflow.com/questions/1213380/Как-перемножить-числа-в-списке

```python3
import math

def grow(arr):
    return math.prod(arr)
```

**Calculate** the product of 😁 😁 😁 _`all the elements`_ in the input **iterable**.

в Библиотеке `math` есть метод(функция) `prod` https://docs.python.org/3/library/math.html#math.prod

---

## Итераторы

- [ ] [Понимание итераторов в Python](https://habr.com/ru/post/488112/)

**Comment by vovs03** [comment]
> https://www.codewars.com/kata/57f780909f7e8e3183000078/train/python
> 
> ```python
> def grow(arr):
>     for i in arr:
>          a = i * i
>     return a
> ```

# Продолжение мысли в твоём варианте:

```python3
def grow(arr):
	product = 1
	for i in arr:
		product *= i
	return product
```


## Много других решений

https://www.codewars.com/kata/57f780909f7e8e3183000078/solutions/python
