### ISSUE TITLE
19.1 Теория `HTML`

### ISSUE THREAD

**Issue by vovs03** [Sergei089/python_ex#31]
# Введение в `HTML`

- [x] https://ru.hexlet.io/courses/layout-designer-basics/lessons/html-intro/theory_unit
- [x] Скриншот всего экрана с компа **Дополнительное задание**
- [ ] включая всю практику из видеоуроков
  - [x] 🗽 1 видео
  - [x] 🗼 2 видео

![image](https://user-images.githubusercontent.com/21124057/211466697-2d14badd-ee28-4205-ae12-16409e9f1442.jpeg) 

прочитать и прислать скриншот о выполнении

Выполнить до 10 января 2023г

**Comment by Sergei089** [comment]
![Screenshot from 2023-01-02 10-12-15](https://user-images.githubusercontent.com/116675434/210203002-41557413-c7d6-416b-8a11-e4d4d623bb06.png)

**Comment by vovs03** [comment]
Прочитал?

**Comment by vovs03** [comment]
@Sergei089  Не сделано

**Comment by vovs03** [comment]
@Sergei089 Проверяю (11янв 23:15, среда) - задание не сделано.

**Comment by vovs03** [comment]
@Sergei089 сделай по порядку, начни с 19.1

**Comment by vovs03** [comment]
@Sergei089 сделай `13.01`

> Прошло 2 недели

**Comment by vovs03** [comment]
@Sergei089 8) sun,15.01 11.31

**Comment by Sergei089** [comment]
![Screenshot_20230116-072818.jpg](https://user-images.githubusercontent.com/116675434/212598766-28ff2914-52dc-4942-88b6-2dae64dd8550.jpg)
![Screenshot_20230116-072245.jpg](https://user-images.githubusercontent.com/116675434/212598778-e3405507-81f3-48ba-b800-bf8eefea8b2d.jpg)

**Comment by vovs03** [comment]
@Sergei089 1 пункт задачи принят +

**Comment by vovs03** [comment]
Практика из видеоуроков не сделана.
