### ISSUE TITLE
19.2 `HTML` Блочная модель

### ISSUE THREAD

**Issue by vovs03** [Sergei089/python_ex#32]
# `хс 3` Блочная модель

> хекслет `html 3 урок`

- [x] https://ru.hexlet.io/courses/layout-designer-basics/lessons/block-model/theory_unit
- [ ] [доп задание](https://youtu.be/0tiWoqzYnDo)
- [ ] Скриншот всего экрана с компа **Дополнительное задание**

прочитать и прислать скриншот о выполнении

**Comment by vovs03** [comment]
@Sergei089 Сюда скриншот прикрепи

**Comment by vovs03** [comment]
@Sergei089 Проверяю (11янв 23:15, среда) - задание не сделано.

**Comment by Sergei089** [comment]
![изображение_2023-01-15_135037723](https://user-images.githubusercontent.com/116675434/212536449-cb1a7056-a175-4073-b96a-7663d1bce08e.png)

**Comment by vovs03** [comment]
> ![изображение_2023-01-15_135037723](https://user-images.githubusercontent.com/116675434/212536449-cb1a7056-a175-4073-b96a-7663d1bce08e.png)
> 
> 

Это не дополнительное задание

**Comment by vovs03** [comment]
не сделано
