### ISSUE TITLE
Задача 21.1 Мотивация + html

### ISSUE THREAD

**Issue by vovs03** [Sergei089/python_ex#36]
- [x] прочитать статью: https://ru.hexlet.io/blog/posts/vozvraschenie-v-koleyu-ili-chto-delat-kogda-opuskayutsya-ruki
- [x] Создать директорию 21_html с файлом `index.html` с отчётом о прочтении этой статьи, включением рисунка и ссылкой на статью, используя теги
- [x] заголовок страницы
- [x] Заголовок отчёта
- [x] Три параграфа `Lorem ipsum` https://ru.lipsum.com/
- [x] заголовок второго уровня/размера
- [x] Параграф + 2 ссылки на прочтённые 2 статьи чтобы открывались в новом окне

**Comment by Sergei089** [comment]
![Screenshot from 2023-01-19 10-53-11](https://user-images.githubusercontent.com/116675434/213385620-e3460c23-ffb9-4134-9180-d269faa9ad71.png)
