### ISSUE TITLE
DNA to RNA Conversion

### ISSUE THREAD

**Issue by vovs03** [Sergei089/python_ex#4]
# DNA to RNA Conversion

## Task

Deoxyribonucleic acid, DNA is the primary information storage molecule in biological systems. It is composed of four nucleic acid bases Guanine ('G'), Cytosine ('C'), Adenine ('A'), and Thymine ('T').

Ribonucleic acid, RNA, is the primary messenger molecule in cells. RNA differs slightly from DNA its chemical structure and contains no Thymine. In RNA Thymine is replaced by another nucleic acid Uracil ('U').

Create a function which translates a given DNA string into RNA.

For example:

""GCAT"  =>  "GCA"
The input string can be of arbitrary length - in particular, it may be empty. All input is guaranteed to be valid, i.e. each input string will only ever consist of 'G', 'C', 'A' and/or 'T'.

---

## Ru- version

> Дезоксирибонуклеиновая кислота, ДНК, является основной молекулой для хранения информации в биологических системах. Он состоит из четырех оснований нуклеиновой кислоты гуанина ("G"), цитозина ("C"), аденина ("A") и тимина ("T").

> Рибонуклеиновая кислота, РНК, является основной молекулой-мессенджером в клетках. РНК незначительно отличается от ДНК своей химической структурой и не содержит тимина. В РНК тимин заменен другой нуклеиновой кислотой урацилом ('U').

:a: Создайте функцию, которая преобразует заданную строку ДНК в РНК.

Например:

""GCAT" => "GCA"
Входная строка может быть произвольной длины - в частности, она может быть пустой. Все входные данные гарантированно будут действительными, т.е. каждая строка ввода всегда будет состоять только из 'G', 'C', 'A' и /или 'T'.

**Comment by vovs03** [comment]
```python
def dna_to_rna(dna):
    return
```

**Comment by vovs03** [comment]
```python

import codewars_test as test
from solution import dna_to_rna

@test.describe("Sample Tests")
def basic_tests():
    @test.it('Basic Test Cases')
    def basic_test_cases():
        test.assert_equals(dna_to_rna("TTTT"), "UUUU")
        test.assert_equals(dna_to_rna("GCAT"), "GCAU")
        test.assert_equals(dna_to_rna("GACCGCCGCC"), "GACCGCCGCC")

```

**Comment by Sergei089** [comment]
# Решение

```python
# DNA.py
dna = "GACCTGCTCGTCCT"

def dna_to_rna(dna):
    return print(dna.replace('T', 'U'))

dna_to_rna(dna)
```

**Comment by Sergei089** [comment]
https://www.codewars.com/join?country=us
