### ISSUE TITLE
создать Linux загрузочную флэшку

### ISSUE THREAD

**Issue by vovs03** [Sergei089/python_ex#7]
- [x] Скачать https://linuxliveusb.com/en/download
- [x] Установить
- [ ] Отформатировать USB-Flash
- [x] Скачать образ LM [тут](https://mirror.yandex.ru/linuxmint/stable/21/linuxmint-21-xfce-64bit.iso) | [сайт LM](https://linuxmint.com/edition.php?id=301)
- [ ] https://www.youtube.com/watch?v=2eNYfqCXhrA&t=4s&ab_channel=%D0%97%D0%B0%D0%BC%D0%B5%D1%82%D0%BA%D0%B8IT%D1%81%D0%BF%D0%B5%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D1%81%D1%82%D0%B0
- [ ] записать FL-USB

**Comment by vovs03** [comment]
# Альтернативные варианты

## macOS

- https://ubuntu.com/tutorials/create-a-usb-stick-on-macos

## Windows

- [ ] https://www.balena.io/etcher/

**Comment by Sergei089** [comment]
![IMG_20230402_210805_561.jpg](https://user-images.githubusercontent.com/116675434/229370820-82f6b420-0ae9-4b1b-b822-ef95e509df53.jpg)

**Comment by vovs03** [comment]
Молодцом!
